### ISSUE TITLE
ru_ru.json language file

### ISSUE THREAD

**Issue by Deni-Naka** [xanthian/variantcraftingtables#16]
[Pastebin link](https://pastebin.com/f0mynt2n)
`{
  "_group":"Creative Tab",
  "itemGroup.variantcraftingtables.vct": "Вариативные верстаки",

  "_comment": "Rename Vanilla",
  "block.minecraft.crafting_table": "Дубовый верстак",

  "_comment1": "Vanilla Variants",
  "block.variantcraftingtables.spruce_crafting_table": "Еловый верстак",
  "block.variantcraftingtables.birch_crafting_table": "Березовый верстак",
  "block.variantcraftingtables.jungle_crafting_table": "Тропический верстак",
  "block.variantcraftingtables.acacia_crafting_table": "Акациевый верстак",
  "block.variantcraftingtables.dark_oak_crafting_table": "Верстак из темного дуба",
  "block.variantcraftingtables.mangrove_crafting_table": "Мангровый верстак",
  "block.variantcraftingtables.crimson_crafting_table": "Багровый верстак",
  "block.variantcraftingtables.warped_crafting_table": "Искажённый верстак",

  "_comment2": "Tech Reborn",
  "block.variantcraftingtables.rubber_crafting_table": "Каучуковый верстак",

  "_comment3": "Blockus",
  "block.variantcraftingtables.bamboo_crafting_table": "Бамбуковый верстак",
  "block.variantcraftingtables.charred_crafting_table": "Обугленный верстак",
  "block.variantcraftingtables.legacy_crafting_table": "Кирпичный верстак",
  "block.variantcraftingtables.white_oak_crafting_table": "Верстак из белого дуба",
  "block.variantcraftingtables.herringbone_acacia_crafting_table": "Зигзагообразный акациевый верстак",
  "block.variantcraftingtables.herringbone_birch_crafting_table": "Зигзагообразный березовый верстак",
  "block.variantcraftingtables.herringbone_bamboo_crafting_table": "Зигзагообразный бамбуковый верстак",
  "block.variantcraftingtables.herringbone_crimson_crafting_table": "Зигзагообразный багровый верстак",
  "block.variantcraftingtables.herringbone_dark_oak_crafting_table": "Зигзагообразный верстак из темного дуба",
  "block.variantcraftingtables.herringbone_jungle_crafting_table": "Зигзагообразный тропический верстак",
  "block.variantcraftingtables.herringbone_oak_crafting_table": "Зигзагообразный дубовый верстак",
  "block.variantcraftingtables.herringbone_spruce_crafting_table": "Зигзагообразный еловый верстак",
  "block.variantcraftingtables.herringbone_warped_crafting_table": "Зигзагообразный искажённый верстак",
  "block.variantcraftingtables.herringbone_charred_crafting_table": "Зигзагообразный обугленный верстак",
  "block.variantcraftingtables.herringbone_white_oak_crafting_table": "Зигзагообразный верстак из белого дуба",

  "_comment4": "Promenade",
  "block.variantcraftingtables.dark_amaranth_crafting_table": "Верстак из темного аморанта",
  "block.variantcraftingtables.cherry_oak_crafting_table": "Верстак из вишневого дуба",
  "block.variantcraftingtables.palm_crafting_table": "Пальмовый верстак",

  "_comment5": "Bewitchment",
  "block.variantcraftingtables.cypress_crafting_table": "Кипарисовый верстак",
  "block.variantcraftingtables.dragons_blood_crafting_table": "Верстак из драконьей крови",
  "block.variantcraftingtables.elder_crafting_table": "Бузиновый верстак",
  "block.variantcraftingtables.juniper_crafting_table": "Можжевельниковый верстак",

  "_comment6": "Botania",
  "block.variantcraftingtables.livingwood_crafting_table": "Верстак из жизнедерва",
  "block.variantcraftingtables.mossy_livingwood_crafting_table": "Верстак из замшелого жизнедерва",
  "block.variantcraftingtables.mossy_dreamwood_crafting_table": "Верстак из замшелого дерева мечтаний",
  "block.variantcraftingtables.dreamwood_crafting_table": "Верстак из дерева мечтанийк",
  "block.variantcraftingtables.shimmerwood_crafting_table": "Верстак из мерцающуего дерева",

  "_comment7": "Wild World",
  "block.variantcraftingtables.wisteria_crafting_table": "Глициньевый верстак",

  "_comment8": "Spectrum",
  "block.variantcraftingtables.black_crafting_table": "Чёрный верстак",
  "block.variantcraftingtables.blue_crafting_table": "Синий верстак",
  "block.variantcraftingtables.brown_crafting_table": "Коричневый верстак",
  "block.variantcraftingtables.cyan_crafting_table": "Голубой верстак",
  "block.variantcraftingtables.gray_crafting_table": "Серый верстак",
  "block.variantcraftingtables.green_crafting_table": "Зеленый верстак",
  "block.variantcraftingtables.light_blue_crafting_table": "Свело-голубой верстак",
  "block.variantcraftingtables.light_gray_crafting_table": "Светло-серый верстак",
  "block.variantcraftingtables.lime_crafting_table": "Лаймовый верстак",
  "block.variantcraftingtables.magenta_crafting_table": "Пурпурный верстак",
  "block.variantcraftingtables.orange_crafting_table": "Оранжевый верстак",
  "block.variantcraftingtables.pink_crafting_table": "Розовый верстак",
  "block.variantcraftingtables.purple_crafting_table": "Фиолетовый верстак",
  "block.variantcraftingtables.red_crafting_table": "Красный верстак",
  "block.variantcraftingtables.white_crafting_table": "Белый верстак",
  "block.variantcraftingtables.yellow_crafting_table": "Жёлтый верстак",
  
  "_comment9" : "Biome Makeover",
  "block.variantcraftingtables.blighted_balsa_crafting_table": "Бальсовый верстак",
  "block.variantcraftingtables.willow_crafting_table": "Ивовый верстак",
  "block.variantcraftingtables.swamp_cypress_crafting_table": "Верстак из болотного кипариса",
  "block.variantcraftingtables.ancient_oak_crafting_table": "Верстак из древнего дуба",

  "_comment10" : "Simple Mango",
  "block.variantcraftingtables.mango_crafting_table": "Манговый верстак",

  "_comment11" : "Encriched",
  "block.variantcraftingtables.bamboo_crafting_table_ve": "Бамбуковый верстак",
  "block.variantcraftingtables.redwood_crafting_table": "Верстак из красной древесины",

  "_comment12" : "Ecologics",
  "block.variantcraftingtables.azalea_crafting_table": "Азалиевый верстак",
  "block.variantcraftingtables.coconut_crafting_table": "Кокосовый верстак",
  "block.variantcraftingtables.flowering_azalea_crafting_table": "Верстак из цветущей азалии",
  "block.variantcraftingtables.walnut_crafting_table": "Верстак из орехового дуба",

  "_comment13" : "Twigs",
  "block.variantcraftingtables.stripped_bamboo_crafting_table": "Обтесанный бамбуковый верстак",

  "_comment14": "Paradise Lost",
  "block.variantcraftingtables.skyroot_crafting_table": "Верстак из небо-дерева",
  "block.variantcraftingtables.golden_oak_crafting_table": "Верстак из золотого дуба",
  "block.variantcraftingtables.crystal_crafting_table": "Кристалический верстак",
  "block.variantcraftingtables.wisteria_crafting_table_pl": "Глициньевый верстак",
  "block.variantcraftingtables.orange_crafting_table_pl": "Оранжевый верстак"

}`

**Comment by xanthian** [comment]
thanks :)
