### ISSUE TITLE
[Mod Compat] <Visual Workbench>

### ISSUE THREAD

**Issue by cymophic** [xanthian/variantcraftingtables#17]
Please list the mod name and a link to the mod and I will look at adding it :)

Visual Workbench by Fuzs_
https://www.curseforge.com/minecraft/mc-mods/visual-workbench

Visual workbench only works with the vanilla crafting table but not with its variants. I assume that it isn't compatible yet. Thanks

**Comment by xanthian** [comment]
Doesn't work on fabric.
Read faq on visual workbench mod
