### ISSUE TITLE
[BUG] Missing everything for 1 of the tables for Blockus

### ISSUE THREAD

**Issue by SplendidAlakey** [xanthian/variantcraftingtables#24]
**Describe the bug**

Herringbone mangrove crafting table is missing translation strings and all textures.

**To Reproduce**

Simply install VCT and Blockus, then get the table from the creative tab.

**Screenshots/Errors**

![2022-10-31_01 37 59](https://user-images.githubusercontent.com/86702831/198910299-3aedebbd-aa89-4c3e-ad42-526be5dc0e96.png)
![2022-10-31_01 38 04](https://user-images.githubusercontent.com/86702831/198910301-4d891ab9-f7ca-49a0-9e89-5a0d08eb08c3.png)

https://gist.github.com/SplendidAlakey/65c0bf3d7ba9814f4c2341beb8f1d6cd

**Mod Version:**

- 3.2.7

**Additional information**

Affects both Quilt and Fabric.

**Comment by xanthian** [comment]
Fixed https://github.com/xanthian/variantcraftingtables/commit/edd739366fb0c91fccb602157deedae58ca081ea
