### ISSUE TITLE
Why on earth are crafting tables stone?

### ISSUE THREAD

**Issue by E-Quiz** [xanthian/variantcraftingtables#27]
Exactly this. Crafting tables are for some reason considered stone, therefore are faster broken with pickaxes, not axes, how it's suppoused to work.

**Comment by xanthian** [comment]
Helpful, lots of info. 😑

Which MC version.
Which mod version.
Custom modpack??

**Comment by xanthian** [comment]
cannot replicate this.
i need more info.

**Comment by xanthian** [comment]
Can't replicate.
Insufficient info. 
User not replying.
