### ISSUE TITLE
[Mod Compat] Enhanced Mushrooms

### ISSUE THREAD

**Issue by MScott7** [xanthian/variantcraftingtables#29]
After installing VCT I noticed that the wood planks added by Enhanced Mushrooms can no longer craft a crafting table, not even a vanilla one. Is this expected behaviour? 

Either way, I'm not sure how you feel about adding support for a 1.18.2 mod, so maybe I can reopen this if/when EM gets updated to 1.19. Just a thought, love how many mods you support already :)

https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms

**Comment by xanthian** [comment]
Vanilla recipe is normally a tag #minecraft:planks
This is overwritten with Oak planks so there is consistency with crafting each type.
Simple solution would be for me to add compatibility.

However, I no longer support 1.18.2, especially if the mod being added is also not being updated.
I prefer to keep my mods support consistent through the versions, where possible.

But its only 2 planks, so I may do this as a one off as you asked nicely 😛

**Comment by xanthian** [comment]
not updating old versions
