### ISSUE TITLE
Warped & crimson crafting tables cause firespread

### ISSUE THREAD

**Issue by yesn0t** [xanthian/variantcraftingtables#4]
Hi, could the warped and crimson tables be changed so that they no longer spread fire ?  
thanks x)

**Comment by xanthian** [comment]
apologies, only just seen this. will take a look.

**Comment by xanthian** [comment]
I've had a look at this, unless I'm misunderstanding the request, but the behaviour is the same with Warped & Crimson Planks?

**Comment by xanthian** [comment]
nvm figured it out.
added them to the 'non_flammable_wood' tag
will add to next release

**Comment by xanthian** [comment]
fixed #8

**Comment by yesn0t** [comment]
hi, sorry for the late reply, i tested 2.1.5 and the result seems to be the same as 2.1, here's a better explanation of my issue :  
when i put down a crafting table in the nether or stronghold portal room, i'm often jumped by fire from nearby lava (in the nether it's unavoidable as there are countless lava pockets hidden in the netherrack walls). Fire doesn't burn the vanilla crafting tables (nor beds, iirc) but placing these blocks near lava still causes a fire to start. Here's a test setup : 
* i put down these 4 blocks next to lava : 
  * oak plank
  * (oak) crafting table
  * warped plank
  * warped crafting table
  
  like this : ![2022-02-06_06 49 55](https://user-images.githubusercontent.com/96038595/152669629-567d14b8-66ee-43f0-b989-ba3c75784170.png)

* now after waiting a few seconds, fire will be started because of the flammable blocks placed close to lava, as you can see, fire will jump towards : 
  * oak plank
  * (oak) crafting table
  * warped crafting table
  
  but fire will not jump to the warped plank, because warped planks not only don't burn, they also don't start fires (like stone, completely neutral to fire)
![2022-02-06_06 50 08](https://user-images.githubusercontent.com/96038595/152669665-47b6ffc8-ad17-488e-b948-e3cbd601e1c5.png)

* after a few more seconds, the oak plank will burn and disappear, leaving behind all 3 other blocks
![2022-02-06_06 50 46](https://user-images.githubusercontent.com/96038595/152669674-49b1b40e-20c6-41dd-9293-f4a75867fa90.png)

* now fire will perpetually light and go out and light again next to both oak and warped crafting tables, which is my main problem : 
![2022-02-06_06 51 21](https://user-images.githubusercontent.com/96038595/152669677-b587f56a-e201-44f8-a08a-6e82cfb9e6a8.png)

So i wish the warped and crimson tables behaved like the warped and crimson planks, by not starting a fire when placed next to lava. Unfortunately i forgot to look at the block tags when i tested this, maybe flammable blocks have a tag that makes them catch fire, instead of the other way around ?

**Comment by xanthian** [comment]
Thanks for the explanation, much appreciated!
I've added the tables to the same tags that warped & crimson planks are in, so that should resolve it.
Will be added with v1.2 hopefully today at some point
