### ISSUE TITLE
Mod Compatibility for Better Azalea wood

### ISSUE THREAD

**Issue by SargRReal** [xanthian/variantcraftingtables#7]
could you maybe add mod compat for Better Azalea wood? https://www.curseforge.com/minecraft/mc-mods/better-azalea

**Comment by xanthian** [comment]
Absolutely!
Will do this next release (may be a week or so)

**Comment by SargRReal** [comment]
Awesome! Looking forward to it:)

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/152682901-8e81739c-5336-4653-8c40-5bc70c9389af.png)

Added with 2.2 (should be up on CF soon)

**Comment by SargRReal** [comment]
ooooo looks amazing:D
